spring:
  profiles:
    active: dev

api:
  permitted:
    access: ${view.index}, ${api.post.registration-request}
  restricted:
    - allow-role:
      name:
      access:
    - allow-role:
      name:
      access:

#      permitted: >
#       ${view.index}
#       ${api.post.registration-request}
  post:
    vehicle: "/vehicle"
    registration-request: "/registration"

view:
  index: "/index"

